### ISSUE TITLE
Upgrade to node 8

### ISSUE THREAD

**Issue by chaupow** [mapbox/route-annotator#27]
Currently route-annotator does not publish binaries for node 8.
This blocks OSRM from upgrading to node 8.

Publishing binaries for node 8 would be awesome

Maybe this is an issue that needs to tell travis to build it with node 8:
https://github.com/mapbox/route-annotator/blob/master/.travis.yml

Maybe there is more to do.

**Comment by danpat** [comment]
Done with https://github.com/mapbox/route-annotator/pull/35

Node8 binaries are available from v0.1.1 onwards
