### ISSUE TITLE
Upgrade to Node 10

### ISSUE THREAD

**Issue by ismaeali** [mapbox/route-annotator#49]
Currently route-annotator does not publish binaries for node 10.
This blocks OSRM from upgrading to node 10.

Publishing binaries for node 10 would be awesome

https://nodejs.org/en/

Maybe this is an issue that needs to tell travis to build it with node 10:
https://github.com/mapbox/route-annotator/blob/master/.travis.yml

Thanks

**Comment by danpaz** [comment]
Closed by #55
