### ISSUE TITLE
annotateRouteFromLonLats returns null

### ISSUE THREAD

**Issue by StephanGeorg** [mapbox/route-annotator#62]
I can't get `annotateRouteFromLonLats()` up and running with OSM extract other then `test/data/winthrop.osm`. The provided example and example data from the repo

```javascript
taglookup.loadOSMExtract(path.join(__dirname,'data/winthrop.osm'), (err) => {
  if (err) throw err;
  var coords = [[-120.1872774,48.4715898],[-120.1882910,48.4725110]];
  taglookup.annotateRouteFromLonLats(coords, (err, wayIds) => {
    if (err) throw err;
    annotator.getAllTagsForWayId(wayIds[0], (err, tags) => {
      if (err) throw err;
      console.log(tags);
    });
  });
});
```

the `annotateRouteFromLonLats` functions returns wayIds but when trying the provided example with OSM Monaco extract

````
curl --remote-name http://download.geofabrik.de/europe/monaco-latest.osm.pbf
node example-server.js monaco-latest.osm.pbf
curl "http://localhost:5000/coordlist/7.422155,43.7368838;7.4230139,43.7369751"
````
`annotateRouteFromLonLats` does not throw but returns `[null]` even if `Constructing RTree ... done` in the initialization.

**Comment by StephanGeorg** [comment]
Turns out that OSM data has changed and updated nodes are not within the 5m radius anymore.

**Comment by yo-han** [comment]
@StephanGeorg But what steps are needed to get it working again? I tried but failed over and over.

**Comment by StephanGeorg** [comment]
"Failed" means that you get no ways from coordinates? 

Maybe you should check my other issue https://github.com/mapbox/route-annotator/issues/64. Seams you have the same problems I have.

**Comment by yo-han** [comment]
Yes, no ways and the example server crashes. I'll look into the other issue. Thanks.
